---
all:
  hosts:
    csr1.njrusmc.net:
    csr2.njrusmc.net:
  vars:
    # connectivity
    ansible_network_os: "ios"  # ios-xe
    ansible_user: "ansible"
    ansible_password: "ansible"
    ansible_python_interpreter: "/usr/bin/env python"

    # network data
    ntp_server1: "192.0.2.1"
    ntp_server2: "192.0.2.2"
